Checkbox  component
neuralbertatech/natUI-react pull request #14
Opened 2023-02-06 06:49 UTC by Frank-1998

Have the checkbox working, usage is in checkbox.tsx under example page.

2023-02-20 03:31 UTC, giancarlopernudisegura reviewed
Seems like you've changed the line endings which messed with the commits. Try running.
```bash
git config --global core.autocrlf true
```
Afterwards, you'll need to convert the files back to unix style line endings.

2023-03-20 18:14 UTC, Frank-1998 commented
Hey Gino, could you check if I have successfully change the line endings please.

2023-03-22 01:46 UTC, giancarlopernudisegura requested changes

2023-03-22 03:40 UTC, Frank-1998 commented
Hey Gino, I think I have resolved your request in the conversation, please have a check.

2023-03-25 06:57 UTC, giancarlopernudisegura requested changes

2023-03-25 06:57 UTC, giancarlopernudisegura commented on src/components/input/CheckBox.tsx
> +      <label >
Should just be nested under the div, not another label tag. For styling, can you pass the style prop (a BaseProps field) to the parent div, and then a spacing between the input and label tag of 2ex?

2023-05-20 18:52 UTC, Frank-1998 commented on src/components/input/CheckBox.tsx
> +      <label >
hey Gino, sorry I didn't see this. I am currently working on it, and I somehow lost the slack for netdev can you add me in the slack?

2023-05-20 19:23 UTC, Frank-1998 commented
@giancarlopernudisegura  I have resolved your request, please take a look, and I am somehow not in the nat-dev slack anymore, could you please add me back? Thank you very much.

2023-05-24 22:59 UTC, giancarlopernudisegura requested changes

2023-05-24 22:59 UTC, giancarlopernudisegura commented on src/components/input/CheckBox.tsx
> +    </div>
Instead of passing the style prop to the `label` element, pass it to the `div` element. Let's also put a hardcoded spacing between the `input` and `label` tags (can be a margin on either element) of `2 ex`.

2023-05-26 23:00 UTC, giancarlopernudisegura approved these changes
Good job!

2023-05-27 00:01 UTC, merged