This is the codeblock
neuralbertatech/natUI-react pull request #7
Opened 2022-12-24 05:05 UTC by GrizzlyScar

2022-12-25 00:21 UTC, giancarlopernudisegura requested changes
I'm getting lots of `Module Not Found` errors. Make sure that the libraries that you're using are in the `package.json` so everything works after running `yarn install`.

2023-01-06 17:49 UTC, GrizzlyScar commented
Can you try the latest commit and see if it works?

2023-01-16 03:34 UTC, giancarlopernudisegura requested changes

2023-01-16 03:34 UTC, giancarlopernudisegura commented on examples/pages/_app.tsx
> +import '../styles/globals.css'
You've included some css import but not the css file.
```
Module not found: Can't resolve '../styles/globals.css'
  3 | import type { AppProps } from "next/app";
  4 | import 'highlight.js/styles/hybrid.css';
> 5 | import '../styles/globals.css'
  6 | 
  7 | function MyApp({ Component, pageProps }: AppProps) {
  8 |   return <Component {...pageProps} />;
```

2023-01-23 23:28 UTC, giancarlopernudisegura commented
Thanks for the submission. I'm going to make some changes before merging the PR.

2023-01-31 06:36 UTC, giancarlopernudisegura approved these changes

2023-01-31 06:36 UTC, merged